name: CreateDependabotIssue
on:
  workflow_dispatch:

jobs:
  check_dependabot:
    runs-on: ubuntu-latest
    steps:
      - env:
          GH_TOKEN: ${{ secrets.TB_PAT }}
        run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/tblanarik/dependabot-demo/dependabot/alerts
